### PR TITLE
Remove duplicate migration

### LINKED ISSUE #135: PG::UndefinedColumn: ERROR:  column "auth_token" of relation "users" does not exist
```
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR rake aborted!
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR StandardError: An error has occurred, this and all later migrations canceled:
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR PG::UndefinedColumn: ERROR:  column "auth_token" of relation "users" does not exist
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR : ALTER TABLE "users" DROP COLUMN "auth_token"
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `async_exec'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:75:in `block (2 levels) in execute'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:74:in `block in execute'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `execute'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:603:in `remove_column'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:871:in `block in method_missing'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `block in say_with_time'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:840:in `say_with_time'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/vendor_bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/migration.rb:860:in `method_missing'
   2019-04-29T11:20:29.12+0200 [APP/PROC/WEB/0] ERR /home/vcap/app/db/migrate/20190320142447_remove_auth_token_from_users.rb:3:in `change'
```

Seems like commit https://github.com/pivotal/postfacto/commit/0cb52be8f695ffad01f881997e9131a33c8006b6 introduced a migration which already exists at https://github.com/pivotal/postfacto/blob/master/api/db/migrate/20190306122214_remove_users_auth_token.rb

Therefore, the above error. Installing the app works when removing the migration file from the above commit

### PR DESCRIPTION
**Pull request by seadowg**
Fixes #135

* [x] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [x] I have made this pull request to the `master` branch

* [x] I have run all the tests using `./test.sh`.

* [x] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

* [x] I have given myself credit in the [humans.txt](https://github.com/pivotal/postfacto/blob/master/humans.txt) file (assuming I want to)

### CODE REVIEW

**Comment by seadowg** [comment]
@liamdarmody it looks like CLA checks might not be running anymore. As far as I know that needs to be on for Pivotal repos.

**Comment by geekygirldawn** [comment]
Note: We're having an issue with the CLA checker bot. This PR should not be merged until we sort out the CLA bot. Sorry about the delay!

**Comment by pivotal-issuemaster** [comment]
@seadowg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/postfacto&pullRequestId=136) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@seadowg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/postfacto&pullRequestId=136)!

**Pull request merged**
