### PR TITLE
More visible deployment instructions

### PR DESCRIPTION
**Pull request by mamachanko**
When opening a folder on Github that contains a `README.md` it is automatically being displayed. This should make the deployment instructions easier to discover.

### CODE REVIEW

**Comment by edbrannin** [comment]
> `cp: cannot stat 'deployment/INSTRUCTIONS.md': No such file or directory`

Looks like there's a filename reference to update somewhere in the code.

(Not a maintainer, just browsing)

**Comment by tom025** [comment]
We are currently working on improving the deployment experience and will include some of the improvements here into what we do. Will look for your feedback when we have finished that work and there is a PR in place.

Closing as this will be superseded shortly and has conflicts.

**Comment by edbrannin** [comment]
I don't suppose you could comment here when that other PR is in place?

**Comment by textbook** [comment]
@edbrannin https://github.com/pivotal/postfacto/pull/152

**Pull request closed without merging**
