### PR TITLE
Bump to Ruby 2.6.3

### LINKED ISSUE #138: Ruby version 2.6.1 not found
Due to https://github.com/cloudfoundry/ruby-buildpack/commit/fca8745a185fc09760cf848f91b72c128a1ec661 Ruby 2.6.1 no longer exists. Changing the version in the `Gemfile` to 2.6.3 seems to be working fine.

### PR DESCRIPTION
**Pull request by HeavyWombat**
Change Ruby version from 2.6.1 to 2.6.3.

Fixes #138.

* [X] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [X] I have made this pull request to the `master` branch

* [X] I have run all the tests using `./test.sh`. _Please note:_  The end to end tests all failed for a reason we could not find out.

* [X] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

* [X] I have given myself credit in the [humans.txt](https://github.com/pivotal/postfacto/blob/master/humans.txt) file (assuming I want to) _Please note:_ Done in #139

### CODE REVIEW

**Comment by HeavyWombat** [comment]
There seems to be chicken-egg problem I cannot solve at the moment. I think the Docker image used by Travis has to be updated first to have Ruby 2.6.3 installed. Please let me know, how you think we can tackle this problem? Thanks in advance!

**Comment by geekygirldawn** [comment]
Note: We're having an issue with the CLA checker bot. This PR should not be merged until we sort out the CLA bot. Sorry about the delay!

**Comment by textbook** [comment]
Yes, looks like [`postfacto/dev`](https://hub.docker.com/r/postfacto/dev/tags) needs to be updated, which means that [`docker/dev/Dockerfile`](https://github.com/pivotal/postfacto/blob/master/docker/dev/Dockerfile) needs to be updated, built, tagged and deployed to Docker Hub. I'll look into getting access to that account to start the ball rolling.

**Comment by seadowg** [comment]
@textbook there is a LastPass that @liamdarmody has access to for shared Postfacto accounts

**Comment by tom025** [comment]
Superseded by: #146

**Pull request closed without merging**
