### PR TITLE
Add emoji selector

### PR DESCRIPTION
**Pull request by jgalilee**
Note: removes transition on background colour
to prevent stutter on blur

Thanks for contributing to postfacto. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

Adds an emoji selector to the edit and create retro input fields

* An explanation of the use cases your change solves

https://github.com/pivotal/postfacto/issues/104

* Links to any other associated PRs

* [x] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [x] I have made this pull request to the `master` branch

* [x] I have run all the tests using `./test.sh`.

* [x] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jgalilee Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/postfacto&pullRequestId=114)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/postfacto&pullRequestId=114) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jgalilee Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/postfacto&pullRequestId=114)!

**Comment by davidje13** [comment]
From looking at the code I suspect this will show up on both desktop and mobile. Can I suggest it is hidden on mobile? iOS and Android already make it very easy to add emoticons through the standard keyboard.

**Comment by jgalilee** [comment]
@davidje13 this is intentional after having tested it. It works well on mobile devices.

**Comment by seadowg** [comment]
@jgalilee would you be able to rebase this on top of master please? Having to change a couple of things to have it run in the right Docker container for testing.

**Comment by jgalilee** [comment]
@seadowg cool, done

**Pull request merged**
