### PR TITLE
Use path routing for server on Cloud Foundry

### LINKED ISSUE #142: PWS: frontend and backend cannot connect because of CORS
I have pushed both the API and Web to the PWS. The Web (frontend) cannot able to connect to the API (backend) because of CORS. How to enable CORS or open container to container communication in PWS

### PR DESCRIPTION
**Pull request by textbook**
- Improve deployment/upgrade scripts and documentation
 - Use `RAILS_RELATIVE_URL_ROOT` to set a relative route for the backend
 - Remove dependency on `CLIENT_ORIGIN`

* A short explanation of the proposed change:

    When deploying to CF, use path routing to mount the server at `<front-end>/api`. This removes any CORS issues, and more closely matches the eventual merged deployment topology.

* An explanation of the use cases your change solves

    Fixes #142

* Links to any other associated PRs

     Also includes the doc/script improvements proposed in #128 and #129

* [x] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [x] I have made this pull request to the `master` branch

* [x] I have run all the tests using `./test.sh` - [passing Travis build](https://travis-ci.org/textbook/postfacto/builds/559858255)

* [x] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

* [x] I have given myself credit in the [humans.txt](https://github.com/pivotal/postfacto/blob/master/humans.txt) file (assuming I want to) - added Max Brauer

### CODE REVIEW

**Comment by textbook** [comment]
Still to be done/figured out:

 - [] Should this be opt-in?
 - [] How do we migrate to this? Need to automate deletion of the old server route?

**Comment by crswty** [comment]
I see this is WIP but I thought I'd mention it in case. I think we can remove the need to set api and websocket  info in config.js and default it to a relative path. This would also fix: #133

**Comment by butzopower** [comment]
I think if the direction is to head towards a single artifact to deploy, this feels like a proper stopgap.  If we are not going to make the single artifact deploy opt-in, then I don't think it makes sense to make this opt-in, either.

Regarding clean up of old routes, I guess we need to figure out how much value there is in it.  Possibly, we could make the deployment script a bit more idempotent and tear down the apps / routes (if they exist) before deploying/upgrading the new ones.

**Comment by textbook** [comment]
@crswty that would be nice, but we need to set the *port* for the sockets and you can't do that without [horrible JavaScript hacks](https://stackoverflow.com/q/6016120/3001761).

**Comment by textbook** [comment]
Closing this in favour of progressing to a single-artifact deployment

**Comment by textbook** [comment]
Now closed out properly via #174

**Pull request closed without merging**
