### PR TITLE
Upgrade all the things

### LINKED ISSUE #349: upgrade to ruby version supported by latest buildpacks
2.6.3 hasn't been supported since Sep 23, 2019 (https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.44). My instances cannot run buildpacks directly from GitHub as https://github.com/pivotal/postfacto/blob/master/deployment/cf/config/manifest.yml tries to do.

How? https://github.com/pivotal/postfacto/blob/master/UPGRADES.md

### PR DESCRIPTION
**Pull request by textbook**
Thanks for contributing to postfacto. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

Upgrades Ruby (2.6.3 -> 2.7.3), Node (12.6.0 -> 14.16.1), Ubuntu (18.04 -> 20.04) and a bunch of dependencies.

* An explanation of the use cases your change solves

Allows you to actually deploy and use the app...

* Links to any other associated PRs

Would fix #349 and #351

Supersedes a bunch of PRs, including Snyk's and #344, #339

* [x] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [x] I have made this pull request to the `master` branch

* [x] I have run all the tests using `./test.sh`.

* [x] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

* [x] I have given myself credit in the [humans.txt](https://github.com/pivotal/postfacto/blob/master/humans.txt) file (assuming I want to)

### CODE REVIEW

**Comment by textbook** [comment]
All of the tests pass in the Docker environment when I run them on my machine, but attempted deployment to CF or Heroku fails due to `LoadError: cannot load such file -- sendgrid_vcap_parser`. Full Heroku output below:

```
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        LoadError: cannot load such file -- sendgrid_vcap_parser
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
remote:        /tmp/build_71fa354c/config/environments/production.rb:31:in `<top (required)>'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/engine.rb:570:in `each'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/engine.rb:570:in `block in <class:Engine>'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:50:in `each'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
remote:        /tmp/build_71fa354c/config/environment.rb:35:in `<top (required)>'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/application.rb:360:in `require_environment!'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.1/lib/rails/application.rb:526:in `block in run_tasks_blocks'
remote:        /tmp/build_71fa354c/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
```

**Comment by textbook** [comment]
The CI build fails because we can't visit the Tanzu blog from the container environment:

```
 1) Felicity when they have not registered before they visit the home page they can learn about retros

     Failure/Error: expect(page).to have_content('How to Run a Really Good Retrospective')

       expected to find text "How to Run a Really Good Retrospective" in "Access Denied\nYou don't have permission to access \"http://tanzu.vmware.com/content/built-to-adapt/how-to-run-a-really-good-retrospective\" on this server.\nReference #18.8c472317.1619180474.76e1cb2"
```

**Comment by textbook** [comment]
The `test-package.sh` script won't work here, because the problem we're solving is that the last release is no longer deployable, so here's the due diligence I've done:

- [x] Deploy a new instance on Heroku: `ENABLE_ANALYTICS=false ./deploy.sh new-postfacto`
    - https://new-postfacto.herokuapp.com/retros/pf-ruby-27/join/nzDCjsTN8JrrnVKxIn8Q5Fzq7PMcKfOP
- [x] Upgrade instance on Heroku (from https://github.com/pivotal/postfacto/pull/293#issuecomment-653453245, was v4.3): `ENABLE_ANALYTICS=false ./upgrade.sh postfacto-postgres-only`
    - https://postfacto-postgres-only.herokuapp.com/retros/demo-retro/join/9UofV5m7rb74iCtq4dlYEYuyFc0MdbLm
- [x] Deploy a new instance on CF: `ENABLE_ANALYTICS=false ./deploy.sh new-postfacto`
    - https://new-postfacto.apps.pcfone.io/retros/pf-ruby-27/join/W1oycatAQT3vNUZF1Az9J0kO5CKZcJPx
- [x] Upgrade instance on CF (was v4.2): `ENABLE_ANALYTICS=false ./upgrade.sh postfacto-jrs-mysql`
    - https://postfacto-jrs-mysql.apps.pcfone.io/retros/test-retro

**Review by th3n3rd — APPROVED** [review]
Looks good to me.

App runs fine locally, no dependencies issues, using the last docker image and deployed to heroku successfully.

**Pull request merged**
