### PR TITLE
New build system for frontend (react-scripts)

### PR DESCRIPTION
**Pull request by davidje13**
This replaces the bespoke frontend build system with a standard react-scripts (create-react-app) build system. This offers many advantages, notably:

- more reliable unit testing
- more reliable builds
- easier configuration options (via environment variables)
- recent versions of most dependencies and all tooling
- simplified build configuration

It will also make it easier to apply further updates to the frontend code.

Shout-out to Katie Moulang and Jennifer Lea for helping with the migration.

This PR also updates and documents all the relevant build scripts, and fixes a duplication bug when adding new items which for some reason became more frequent with this change.

**Notes**

* I have updated the Dockerfile to use Node 11, and removed old tools which are no-longer required.

* I have removed polyfills, as some are provided by default and I'm not sure which extra polyfills are still required. Since there are no officially supported browsers, I have tested this only in Chrome (using the standard testing suite).

* Jasmine has been replaced with Jest for running tests, as this is the only option provided by react-scripts. Some Jasmine matchers are still used, and seem to play somewhat-nicely with Jest. Some matchers have been wrapped with Jest-specific code.

**TODO**

* [x] <s>The published docker image needs updating.</s> This is now using a specific version (`postfacto/postfacto:node11`).

* [ ] Manually test in FireFox and Edge before merging, confirm that we are OK to remove polyfills.

* [ ] Thew build / deploy scripts should be tested with PCF/CF/Heroku deployments.

* [x] <s>I have **not** updated any CI scripts, as I have been told the Concourse integration is being removed.</s> Working on Travis now.

---

* [x] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [x] I have made this pull request to the `master` branch

* [x] I have run all the tests using `./test.sh`.

* [x] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

### CODE REVIEW

**Comment by davidje13** [comment]
The Travis build failure ("Object.entries is not a function") is due to the docker image still using Node 6. Rebuilding with the updated Dockerfile should fix it.

**Comment by davidje13** [comment]
There is a build issue on Travis which is related to users/permissions. I'm unable to replicate it locally so I'm going to have to push a few diagnosis commits to this branch. Apologies for the noise! I'll try to tidy it up later.

**Comment by seadowg** [comment]
@davidje13 could you check these changes through in Firefox and the latest Microsoft browser

**Comment by davidje13** [comment]
I have completed manual testing in latest FireFox (on OSX) and Safari. It runs fine for creating a retro, adding / editing / deleting items, adding / editing / ticking / deleting action items, syncing between windows, changing settings (password), focussing / completing items, archiving, viewing archives.

Still need to test Edge

**Comment by davidje13** [comment]
Same testing in Edge works fine too.

I used a windows 10/Edge VM from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and changed Postfacto's config.js to use 10.0.2.2:4000 instead of localhost:4000.

**Comment by davidje13** [comment]
A quick test shows that even the first page does not load in IE11. It complains about Object.assign, which would need a polyfill.

**Comment by seadowg** [comment]
@davidje13 thanks so much for running through the browsers. Going to go ahead and merge this.

**Pull request merged**
