### PR TITLE
Notes deploy from source is not supported

### PR DESCRIPTION
**Pull request by benlachman**
Makes issues like pivotal/postfacto#167 & pivotal/postfacto#167 less likely to be created in the future.

Thanks for contributing to postfacto. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

> Quick update to README to solve my (duplicate) issue with trying to deploy from source.

* An explanation of the use cases your change solves:

> Anyone who defaults to deploying from source.

* [x] I have reviewed the [contributing guide](https://github.com/pivotal/postfacto/blob/master/CONTRIBUTING.md)

* [x] I have made this pull request to the `master` branch

* [x] I have run all the tests using `./test.sh`.

* [x] I have added the [copyright headers](https://github.com/pivotal/postfacto/blob/master/license-header.txt) to each new file added

* [x] I have given myself credit in the [humans.txt](https://github.com/pivotal/postfacto/blob/master/humans.txt) file (assuming I want to)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@benlachman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/postfacto&pullRequestId=170)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal/postfacto&pullRequestId=170) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@benlachman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal/postfacto&pullRequestId=170)!

**Comment by seadowg** [comment]
I totally agree that this is a common issue but it does feel like this just adds more text for people to ignore - the first paragraph links to the releases page. 

I do wonder if making sure the Github links to [postfacto.io](https://postfacto.io) and trying to push that as "the shareable link" might help dissuade people from trying to default to installing source. I'm not quite sure why the website is so secret at the moment.

**Comment by benlachman** [comment]
@seadowg I (perhaps stupidly) wasted *hours* on this. I read through the readme ~at least 3~ many times and the current wording just didn't make me realize that I was doing it all wrong. It took me finally getting over my dislike of raising "support" GH issues to figure out the error in my ways. I think there should be something explicit for stubborn dummies like myself. 😫

**Comment by crswty** [comment]
I'm going to merge this in for now because I agree it's causing issues.

That said, we are looking to provide a docker based solution also so I think the whole section will be reworked once that happens and hopefully we won't need this clarifier.

**Pull request merged**
